UPDATED sqlite3 gem to avoid error
load error occured when rails app:update
LoadError: Error loading the 'sqlite3' Active Record adapter.
Missing a gem it depends on? can't activate sqlite3 (>= 2.1), already activated sqlite3-1.6.9